export const environment = {
  apiAuthorsUrl: `https://biblioteka.simonovicp.com/api/authors`,
  token: `Bearer 230|9PBBxdYgaDrUGgQZQiRmDkMwQFpcHqGaHVYDDNej`,
  apiStoreAuthors: `https://biblioteka.simonovicp.com/api/authors/store`,
  apiUsersUrl: `https://biblioteka.simonovicp.com/api/users`,
  apiUsersStore: 'https://biblioteka.simonovicp.com/api/users/store',
  apiBooks: 'https://biblioteka.simonovicp.com/api/books',
  apiPublishers: 'https://biblioteka.simonovicp.com/api/publishers',
  apiGenres: 'https://biblioteka.simonovicp.com/api/genres',
  apiCategories: 'https://biblioteka.simonovicp.com/api/categories',
  apiScripts: 'https://biblioteka.simonovicp.com/api/scripts',
  apiBookbinds: 'https://biblioteka.simonovicp.com/api/bookbinds',
  apiFormats: 'https://biblioteka.simonovicp.com/api/formats',
  apiLanguages: 'https://biblioteka.simonovicp.com/api/languages',
  apiBookUpdate: 'https://biblioteka.simonovicp.com/api/books',
  apiBookStore: 'https://biblioteka.simonovicp.com/api/books/store',
  apiRecordsBorrow: 'https://biblioteka.simonovicp.com/api/books/borrows',
};
